base_url = "https://blog.criphc.com"
title = "网路飘游"
description = "不只网路，不止飘游。"

compile_sass = true
generate_feeds = true


[extra]

title_micro = "Criphc今天睡了吗？"
description_micro = "祝您夜夜好眠。"

seo = true
author = "Criphc"
ogimage = "blog.png"
description = "不只网路，不止飘游"

footer_links = [
    {url = "$BASE_URL/about#title", name = "关于"},
    {url = "$BASE_URL/atom.xml", name = "订阅"}
]
footer_links_micro = [
    {url = "$BASE_URL/", name = "返回主页"},
    {url = "$BASE_URL/micro/atom.xml", name = "订阅本页"}
]